tinyMCE.addI18n('pl.advanced',{
style_select:"Styl",
font_size:"Rozmiar czcionki",
fontdefault:"Rodzaj czcionki",
block:"Format",
paragraph:"Paragraf",
div:"Div",
address:"Adres",
pre:"Czcionka o stałej szerokości",
h1:"Nagłówek 1",
h2:"Nagłówek 2",
h3:"Nagłówek 3",
h4:"Nagłówek 4",
h5:"Nagłówek 5",
h6:"Nagłówek 6",
blockquote:"Wydzielony blok",
code:"Kod",
samp:"Próbka kodu",
dt:"Definicja terminu ",
dd:"Opis terminu",
bold_desc:"Pogrubienie (Ctrl+B)",
italic_desc:"Kursywa (Ctrl+I)",
underline_desc:"Podkreślenie (Ctrl+U)",
striketrough_desc:"Przekreślenia",
justifyleft_desc:"Wyrównaj do lewej",
justifycenter_desc:"Wycentruj",
justifyright_desc:"Wyrównaj do prawej",
justifyfull_desc:"Równanie do prawej i lewej",
bullist_desc:"Lista nienumerowana",
numlist_desc:"Lista numerowana",
outdent_desc:"Cofnij wcięcie",
indent_desc:"Wcięcie",
undo_desc:"Cofnij (Ctrl+Z)",
redo_desc:"Ponów (Ctrl+Y)",
link_desc:"Wstaw/edytuj link",
unlink_desc:"Usuń link",
image_desc:"Wstaw/edytuj obraz",
cleanup_desc:"Wyczyść nieuporządkowany kod",
code_desc:"Edytuj źródło HTML",
sub_desc:"Indeks dolny",
sup_desc:"Indeks górny",
hr_desc:"Wstaw poziomą linię",
removeformat_desc:"Usuń formatowanie",
custom1_desc:"Twój niestandardowy opis tutaj",
forecolor_desc:"Wybierz kolor tekstu",
backcolor_desc:"Wybierz kolor tła",
charmap_desc:"Wstaw niestandardowy znak",
visualaid_desc:"Przełącz widoczność wskaźników i niewidzialnych elementów",
anchor_desc:"Wstaw/edytuj kotwicę",
cut_desc:"Wytnij",
copy_desc:"Kopiuj",
paste_desc:"Wklej",
image_props_desc:"Właściwości obrazka",
newdocument_desc:"Nowy dokument",
help_desc:"Pomoc",
blockquote_desc:"Blok cytatu",
clipboard_msg:"Akcje Kopiuj/Wytnij/Wklej nie są dostępne w Mozilli i Firefox.\nCzy chcesz więcej informacji o tym problemie?",
path:"Ścieżka",
newdocument:"Czy jesteś pewnien, ze chcesz wyczyścić całą zawartość?",
toolbar_focus:"Przeskocz do przycisków narzędzi - Alt+Q, Przeskocz do edytora - Alt-Z, Przeskocz do elementu ścieżki - Alt-X",
more_colors:"Więcej kolorów"
});