tinyMCE.addI18n('pl.advanced_dlg',{
about_title:"O TinyMCE",
about_general:"O TinyMCE",
about_help:"Pomoc",
about_license:"Licencja",
about_plugins:"Wtyczki",
about_plugin:"Wtyczka",
about_author:"Autor",
about_version:"Wersja",
about_loaded:"Załadowane wtyczki",
anchor_title:"Wstaw/Edytuj zakotwiczenie",
anchor_name:"Nazwa zakotwiczenia",
code_title:"Edytor źródła HTML",
code_wordwrap:"Zawijanie słów",
colorpicker_title:"Wybierz kolor",
colorpicker_picker_tab:"Wybieranie",
colorpicker_picker_title:"Wybieranie kolorów",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta kolorów",
colorpicker_named_tab:"Nazwane",
colorpicker_named_title:"Nazwane kolory",
colorpicker_color:"Kolor:",
colorpicker_name:"Nazwa:",
charmap_title:"Wybierz niestandardowy znak",
image_title:"Wstaw/Edytuj obraz",
image_src:"URL obrazka",
image_alt:"Opis obrazka",
image_list:"Lista obrazków",
image_border:"Ramka",
image_dimensions:"Rozmiary",
image_vspace:"Pionowy odstęp",
image_hspace:"Poziomy odstęp",
image_align:"Wyrównanie",
image_align_baseline:"Linia bazowa",
image_align_top:"Góra",
image_align_middle:"Środek",
image_align_bottom:"Dolny",
image_align_texttop:"Górny tekst",
image_align_textbottom:"Dolny tekst",
image_align_left:"Lewy",
image_align_right:"Prawy",
link_title:"Wstaw/edytuj link",
link_url:"Link URL",
link_target:"Cel",
link_target_same:"Otwórz link w tym samym oknie",
link_target_blank:"Otwórz link w nowym oknie",
link_titlefield:"Tytuł",
link_is_email:"URL który otworzyłeś wydaje się być adresem mailowym, czy chcesz dodać odpowiedni prefix mailto: ?",
link_is_external:"URL który otworzyłeś wydaje się być zewnętrznym linkiem, czy chcesz dodać wymagany prefix http:// ?",
link_list:"Lista linków"
});